### ISSUE TITLE
Do not work with 2.4.1

### ISSUE THREAD

**Issue by Mcherb** [Alberplz/angular2-color-picker#74]
The name of the ColorPickerModule is changed to "e" when imported (Runtime error). I'm using the color picker in a module that is loaded in lazy mode (It works fine with angular version 2.1.0).

here is the error stack:

 Uncaught (in promise): Error: Unexpected value 'e' imported by the module 'ParametrageAnomalieModule'
Error: Unexpected value 'e' imported by the module 'ParametrageAnomalieModule'
    at SyntaxError.BaseError [as constructor] (http://localhost:8080/javascripts/bundle.js:19196:30) [angular]
    at new SyntaxError (http://localhost:8080/javascripts/bundle.js:19394:19) [angular]
    at http://localhost:8080/javascripts/bundle.js:35721:47 [angular]
    at Array.forEach (native) [angular]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/javascripts/bundle.js:35706:52) [angular]
    at JitCompiler._loadModules (http://localhost:8080/javascripts/bundle.js:44889:67) [angular]
    at JitCompiler._compileModuleAndComponents (http://localhost:8080/javascripts/bundle.js:44849:55) [angular]
    at JitCompiler.compileModuleAsync (http://localhost:8080/javascripts/bundle.js:44815:24) [angular]
    at ModuleBoundCompiler.compileModuleAsync (http://localhost:8080/javascripts/bundle.js:45230:34) [angular]
    at MergeMapSubscriber.project (http://localhost:8080/javascripts/bundle.js:72003:235) [angular]
    at MergeMapSubscriber._tryNext (http://localhost:8080/javascripts/bundle.js:78514:28) [angular]
    at MergeMapSubscriber._next (http://localhost:8080/javascripts/bundle.js:78504:19) [angular]
    at MergeMapSubscriber.Subscriber.next (http://localhost:8080/javascripts/bundle.js:59296:19) [angular]
    at http://localhost:8080/javascripts/bundle.js:77469:37 [angular]
    at SyntaxError.BaseError [as constructor] (http://localhost:8080/javascripts/bundle.js:19196:30) [angular]
    at new SyntaxError (http://localhost:8080/javascripts/bundle.js:19394:19) [angular]
    at http://localhost:8080/javascripts/bundle.js:35721:47 [angular]
    at Array.forEach (native) [angular]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/javascripts/bundle.js:35706:52) [angular]
    at JitCompiler._loadModules (http://localhost:8080/javascripts/bundle.js:44889:67) [angular]
    at JitCompiler._compileModuleAndComponents (http://localhost:8080/javascripts/bundle.js:44849:55) [angular]
    at JitCompiler.compileModuleAsync (http://localhost:8080/javascripts/bundle.js:44815:24) [angular]
    at ModuleBoundCompiler.compileModuleAsync (http://localhost:8080/javascripts/bundle.js:45230:34) [angular]
    at MergeMapSubscriber.project (http://localhost:8080/javascripts/bundle.js:72003:235) [angular]
    at MergeMapSubscriber._tryNext (http://localhost:8080/javascripts/bundle.js:78514:28) [angular]
    at MergeMapSubscriber._next (http://localhost:8080/javascripts/bundle.js:78504:19) [angular]
    at MergeMapSubscriber.Subscriber.next (http://localhost:8080/javascripts/bundle.js:59296:19) [angular]
    at http://localhost:8080/javascripts/bundle.js:77469:37 [angular]
    at resolvePromise (http://localhost:8080/javascripts/bundle.js:16208:32) [angular]
    at resolvePromise (http://localhost:8080/javascripts/bundle.js:16193:18) [angular]
    at http://localhost:8080/javascripts/bundle.js:16242:18 [angular]
    at Object.onInvokeTask (http://localhost:8080/javascripts/bundle.js:50105:42) [angular]
    at ZoneDelegate.invokeTask (http://localhost:8080/javascripts/bundle.js:15996:41) [angular]
    at Zone.runTask (http://localhost:8080/javascripts/bundle.js:15873:48) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:8080/javascripts/bundle.js:16140:36) [<root>]

**Comment by garciparedes** [comment]
Same problem here

**Comment by sconix** [comment]
I have made a PR which fixes this library to be AOT compatible + some other fixes. You can try it by installing from here: git://github.com/zefoy/angular2-color-picker.git#npm-package

**Comment by jiggy1com** [comment]
Mine broke somewhere along the line, I think when I upgraded to the (at the time) current version of 2.4.3. ... Since I'm testing/building my app (not ready for prod) I just took it out. Today I tested it again and it's working fine. I'm running @angular/core 2.4.3 Here's a snippet of my package.json

```
 "dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/forms": "2.4.1",
    "@angular/http": "2.4.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/router": "3.4.1",
    "@angular/upgrade": "2.4.1",
    "angular2-color-picker": "^1.3.0",
    "angular2-in-memory-web-api": "0.0.21",
    "bootstrap": "^3.3.7",
    "codemirror": "^5.21.0",
    "core-js": "^2.4.1",
    "dragula": "^3.7.2",
    "mdbootstrap": "^4.2.0",
    "ng2-bootstrap": "1.1.16-9",
    "ng2-charts": "^1.4.1",
    "ng2-codemirror": "^1.0.1",
    "ng2-dragula": "^1.2.2",
    "ng2-file-upload": "^1.1.4-2",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.1",
    "systemjs": "0.19.41",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "concurrently": "3.1.0",
    "lite-server": "^2.2.0",
    "typescript": "^2.0.10"
  },
```
... but it's tough to keep up w/ the latest versions (not just my code, but third party libs, too).

**Comment by jaumard** [comment]
@sconix this repo seems abandoned by his owner, you should publish your version under npm under new name and enable issues if you want to support it, maybe allow some core maintainers can be a good things

**Comment by sconix** [comment]
Yes I am thinking of doing that since I would not mind to keep maintaining this. My current plan is that if I don't hear from @Alberplz soon I will make a new release with different name. At the same time I would like to make sure that the lib works with the upcoming Angular 4. 

Has anybody seen any recommendations or have a good suggestion how to rename this library? I think now is anyway good time to release under different name Angular 4 is out quite soon, but I think they don't want everything named angular4-* and somehow ng2 makes also less sense once version 4 is out.

**Comment by jaumard** [comment]
@sconix why not just ng-color-picker and under description just say it's start at angular v2. Make sense for me since having the angular version under the package name doesn't make sense if multiple version are supported. Let us know when you publish it I'll switch to yours :) I'll see if I can help on it

**Comment by sconix** [comment]
Thanks, I will post here once I have published the new package.

**Comment by Alberplz** [comment]
Ive been bussy but new release to 2.4 is published

**Comment by jaumard** [comment]
@Alberplz not working :( something went wrong on your publishing I think https://github.com/Alberplz/angular2-color-picker/issues/81

**Comment by mcherb** [comment]
works well for me, tks :)
